title: TPEN Interfaces
description: Useful Interfaces for TPEN 3
collections: 
  cookbook:
    label: TPEN Cookbook
    output: true
  classes:
    label: Class
    output: true
theme: jekyll-theme-modernist

permalink: pretty
plugins:
  - jekyll-redirect-from
exclude:
  - LICENSE-CONTENT
